## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [2]:
N = int(input("Введите число N: "))

x = np.arange(N-1,-1,-1)

#x = np.array([n for n in range(N)])[::-1]

x

Введите число N: 20


array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [48]:
N = int(input("Введите число N: "))

d = np.diag(np.arange(N,-1,-1))

print(d)

print(sum(sum(d)))

sum(np.diag(d))

Введите число N: 15
[[15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 14  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 13  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 12  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 11  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
120


120

## Задание 3
Решите систему уравнений:
* 4x + 2y + z = 4
* x + 3y = 12
* 5y + 4z = -3

In [41]:
from numpy import linalg

m = np.array([[4,2,1],[1,3,0],[0,5,4]]) #left part
print(m)
v = np.array([4,12,-3])#right part
print("\n")
print(v)
np.linalg.solve(m,v)

[[4 2 1]
 [1 3 0]
 [0 5 4]]


[ 4 12 -3]


array([ 0.46666667,  3.84444444, -5.55555556])

## Задание 4
Вам подаются на вход два вектора a и b в трехмерном пространстве.Заполните их случайными числами. Реализуйте их скалярное произведение с помощью NumPy.

In [58]:
a = np.random.rand(3,3,3)
b = np.random.rand(3,3,3)
#print(a)
#print(b)
np.dot(a,b)

array([[[[0.45138045, 0.45718116, 0.94488684],
         [0.82423112, 0.76700749, 0.19967983],
         [0.20674134, 0.62233751, 0.53870002]],

        [[0.80164945, 0.64798553, 0.19541331],
         [0.58644344, 0.59846057, 0.20431959],
         [0.42579022, 0.57681468, 0.63051383]],

        [[0.66898909, 0.66700909, 0.68488226],
         [0.90506367, 0.59924593, 0.27579622],
         [0.35464355, 0.53377345, 0.6729275 ]]],


       [[[0.92309938, 0.91928248, 0.97299016],
         [1.25887791, 0.85156249, 0.38019766],
         [0.48703147, 0.75462705, 0.93273881]],

        [[0.52812727, 0.53669571, 0.60861521],
         [0.75878079, 0.50161252, 0.22661335],
         [0.27804578, 0.4404963 , 0.54740467]],

        [[1.31495959, 1.23511934, 1.66657371],
         [1.79489987, 1.61741943, 0.4894615 ],
         [0.6520136 , 1.38037795, 1.34127851]]],


       [[[0.790774  , 0.64085606, 0.67506943],
         [0.78331689, 0.96614657, 0.21094974],
         [0.38591106, 0.84157544, 0.70399028